### ISSUE TITLE
Overlapping digits

### ISSUE THREAD

**Issue by JuiP** [sugarlabs/jamath-activity#15]
- The Digits which fall down often overlap and are hard to read.
- Overlapping digits lead to the wrong answer being selected (because it overlaps with the correct answer)

Edit:
The overlapping is seen as `juego.py` uses `randint()` to generate the coordinates where the answers are rendered.
Work-around would be to have a specific set of coordinates stored instead of `randint()` generation. However, it should be noted that the correct answer should not always appear in the same position.

**Comment by chimosky** [comment]
We can have a set of coordinates that don't overlap and have `randint` get random coordinates from that instead.

**Comment by JuiP** [comment]
Well that seems like a good idea but that does not ensure that we don't end up with the same coordinates. It might be less likely but the problem of overlapping digits might still occur.
