### ISSUE TITLE
Cannot end an instance of activity.

### ISSUE THREAD

**Issue by sourabhaa** [sugarlabs/jamath-activity#19]
There is no option to quit an instance of the game. Instead, a player has to restart the activity. As a result, there is no scope to reach the end pont of the game i.e, to win or lose the game.
One posibility to work around would be to add a timer to end an instance and display the score of that instance and the high score of that session. A quit and restart option could be availed to end the instance before the end of timer.

**Comment by chimosky** [comment]
The activity has a `Stop` button at the top right of the screen where you can end the activity instance, if I understand correctly you want a button to pause, end or restart the game while in-game.

**Comment by sourabhaa** [comment]
I think you are referring to the ```Stop``` button as shown in screenshot.

![JAMath-quit-button](https://user-images.githubusercontent.com/43743186/112716930-61060d00-8f0f-11eb-888f-dc627a72b67e.jpeg)

This will end the instance of activity without giving out the result. I think it would encourage children to compete more if there is an end result for each game i.e, win/lose. To add this feature, a timer could be set for playing the game each time, and the high score could be shown after each game which decides the win/lose. 

Yes, end and reset buttons could be added while in-game as extra features.

**Comment by chimosky** [comment]
I like your idea @sourabhaa and I think this is something that should be implemented, I can't implement this at the moment but if you can I'll gladly test and review. Thanks.

**Comment by JuiP** [comment]
> I like your idea @sourabhaa and I think this is something that should be implemented, I can't implement this at the moment but if you can I'll gladly test and review. Thanks.

+1

However, I do not support the idea of adding a pause button. Because that defeats the purpose of the activity; the child can pause the activity take extra time to calculate and click play. End and restart buttons seem good :)

**Comment by sourabhaa** [comment]
> > I like your idea @sourabhaa and I think this is something that should be implemented, I can't implement this at the moment but if you can I'll gladly test and review. Thanks.
> 
> +1
> 
> However, I do not support the idea of adding a pause button. Because that defeats the purpose of the activity; the child can pause the activity take extra time to calculate and click play. End and restart buttons seem good :)

Agreed. I'd love to give it a try!

**Comment by sourabhaa** [comment]
fixed in #23
